# Generated by Django 2.2.6 on 2019-10-03 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventfinder', '0002_auto_20191003_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(default='', related_name='attendees', to=settings.AUTH_USER_MODEL),
        ),
    ]
